
language: rust
services: docker

matrix:
  include:

    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

before_install:
  - rustup self update
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - cargo test --release
  - cargo run --example main
  - cargo build --release

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo
